name:          Przewodnik stylu
description:   Porady jak pisać dobry i ładny kod w HTML i CSS.
url:           http://maciej.żok.pl/przewodnik-stylu

markdown:      rdiscount
permalink:     pretty
pygments:      true
